name: voice_example
description: Demonstrates how to use the voice plugin.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cached_network_image: 3.0.0
  flutter_cache_manager: 3.0.2
  http: 0.13.3
  provider: 6.0.1
  internet_connection_checker: ^0.0.1
  easy_dynamic_theme: ^2.2.0
  sembast: 3.0.2
  path_provider: 2.0.1
  url_launcher: ^6.0.4
  image_picker: 0.7.5+2
  progress_dialog: 1.2.4
  easy_localization: 3.0.0
  launch_review: 3.0.1
  package_info: 2.0.0
  fluttertoast: 8.0.7
  permission_handler: 7.1.0
  shared_preferences: 2.0.9
  firebase_core: ^1.3.0
  azlistview: 1.1.1
  lpinyin: 2.0.3
  flutter_slidable: 0.6.0
  flutter_switch: 0.3.1
  #  pusher_client: 1.1.3
  graphql: ^5.0.0-nullsafety.5
  firebase_messaging: 10.0.0
  quiver: ^3.0.1
  android_alarm_manager: ^2.0.0
  app_settings: ^4.1.0
  workmanager: ^0.4.1
  carousel_slider: 4.0.0-nullsafety.0
  flutter_svg: ^0.22.0
  in_app_update: ^2.0.0
  flutter_screenutil: ^5.0.0+2
  scrollable_positioned_list: ^0.1.10
  phone_number: ^0.12.0
  audioplayers: ^0.19.1
  flex_color_picker: ^2.1.1
  image_cropper: ^1.4.0
  #  firebase_crashlytics: ^2.0.6
  timeago: ^3.1.0
  flutter_spinkit: ^5.0.0
  flutter_slider_drawer: ^2.0.0
  flutter_staggered_grid_view: ^0.4.0
  device_info_plus: ^2.1.0
  event_bus: ^2.0.0
  audio_wave: ^0.0.3
  jwt_decode: ^0.3.1
  substring_highlight: ^1.0.33
  functional_widget: ^0.9.0+2
  wakelock: ^0.5.3+3
  no_context_navigation: ^2.1.2
  mockito: ^5.0.15
  page_transition: ^2.0.2
  flutter_libphonenumber: ^1.2.0
  intl_phone_number_input: ^0.7.0+2
  fcm_unrealistic_heartbeat: ^0.0.3
  device_preview: ^1.0.0
  android_alarm_manager_plus: ^1.2.0
  contacts_service: ^0.6.3
  intercom_flutter: ^5.2.0
  shimmer: ^2.0.0
  sliding_up_panel: ^2.0.0+1
  percent_indicator: ^2.1.7+2
  encrypt: ^5.0.1

  flutter_incall_manager:
    git:
      url: https://gitlab.com/dristisushan/flutter-incall-manager
      ref: main

  flutter_stetho:
    git:
      url: git://github.com/jasonlewicki/flutter_stetho.git
      ref: master

  voice:
    path: ../
#    git:
#      url: git://github.com/JoshanTandukar/twilio_voice.git


  audio_manager:
    git:
      url: git://github.com/JoshanTandukar/audio_manager-master.git

  awesome_notifications:
    git:
      url: https://gitlab.com/dristisushan/awesome_notification
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: 0.9.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/icon.png"
  image_path_android: "assets/launcher/icon.png"
  adaptive_icon_background: "assets/launcher/background.png"
  adaptive_icon_foreground: "assets/launcher/foreground.png"
# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/audio/beep.mp3
    - assets/audio/chime.mp3
    - assets/audio/sms.mp3
    - assets/audio/tone.mp3
    - assets/audio/incoming.wav
    - assets/fonts/CustomIcon.ttf
    - assets/fonts/Heebo-Black.ttf
    - assets/fonts/Heebo-Bold.ttf
    - assets/fonts/Heebo-ExtraBold.ttf
    - assets/fonts/Heebo-Light.ttf
    - assets/fonts/Heebo-Medium.ttf
    - assets/fonts/Heebo-Regular.ttf
    - assets/fonts/Heebo-Thin.ttf
    - assets/fonts/manrope-bold.otf
    - assets/fonts/manrope-extrabold.otf
    - assets/fonts/manrope-light.otf
    - assets/fonts/manrope-medium.otf
    - assets/fonts/manrope-regular.otf
    - assets/fonts/manrope-semibold.otf
    - assets/fonts/manrope-thin.otf
    - assets/images/add_member.png
    - assets/images/block_contact.png
    - assets/images/delete_contact.png
    - assets/images/deleted_workspace.png
    - assets/images/empty_call.png
    - assets/images/empty_contact.png
    - assets/images/empty_member.png
    - assets/images/empty_message.png
    - assets/images/empty_notes.png
    - assets/images/empty_numbers.png
    - assets/images/empty_tags.png
    - assets/images/empty_teams.png
    - assets/images/get_started.png
    - assets/images/icon_call.svg
    - assets/images/icon_switch.png
    - assets/images/image_credit.png
    - assets/images/invitation.png
    - assets/images/logo.png
    - assets/images/logo_maincolor.png
    - assets/images/no_conversation.png
    - assets/images/no_internet.png
    - assets/images/no_internet_icon.svg
    - assets/images/no_recording.svg
    - assets/images/workspace.svg
    - assets/images/private_number.png
    - assets/images/smartphone.png
    - assets/images/icon_password_link.png
    - assets/images/icon_cart.png
    - assets/images/icon_no_search_results.png
    - assets/images/image_card.png
    - assets/images/icon_emergency.png
    - assets/images/
    - assets/langs/da-DK.json
    - assets/langs/de-DE.json
    - assets/langs/en-US.json
    - assets/langs/es-ES.json
    - assets/langs/fr-FR.json
  fonts:
    - family: HeeboRegular
      fonts:
        - asset: assets/fonts/Heebo-Regular.ttf
    - family: HeeboMedium
      fonts:
        - asset: assets/fonts/Heebo-Medium.ttf
    - family: HeeboBlack
      fonts:
        - asset: assets/fonts/Heebo-Black.ttf
    - family: HeeboBold
      fonts:
        - asset: assets/fonts/Heebo-Bold.ttf
    - family: HeeboExtraBold
      fonts:
        - asset: assets/fonts/Heebo-ExtraBold.ttf
    - family: HeeboLight
      fonts:
        - asset: assets/fonts/Heebo-Light.ttf
    - family: HeeboThin
      fonts:
        - asset: assets/fonts/Heebo-Thin.ttf
    - family: CustomIcon
      fonts:
        - asset: assets/fonts/CustomIcon.ttf
    - family: ManropeRegular
      fonts:
        - asset: assets/fonts/manrope-regular.otf
    - family: ManropeMedium
      fonts:
        - asset: assets/fonts/manrope-medium.otf
    - family: ManropeBold
      fonts:
        - asset: assets/fonts/manrope-bold.otf
    - family: ManropeExtraBold
      fonts:
        - asset: assets/fonts/manrope-extrabold.otf
    - family: ManropeLight
      fonts:
        - asset: assets/fonts/manrope-light.otf
    - family: ManropeSemiBold
      fonts:
        - asset: assets/fonts/manrope-semibold.otf
    - family: ManropeThin
      fonts:
        - asset: assets/fonts/manrope-thin.otf
