/// Flutter icons CustomIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcon
///      fonts:
///       - asset: fonts/CustomIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcon {
  CustomIcon._();

  static const _kFontFam = 'CustomIcon';
  static const _kFontPkg = null;

  static const IconData ic_chair = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_clothe = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_delete = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_edit_profile = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_furniture = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_history = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_home = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_logout = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_mail = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_notification = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_order_history = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_profile = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_shipping_address = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_shoes = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_store = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_wishlist = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_beauty = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_bike = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_call = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_cart = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_filter = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_shield = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_check_outline = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_edit = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_more = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_grid = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_pin = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_user = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_card = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_plus_outline = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_minu_outline = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_check = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_misc = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
