
class Const
{
  Const._();

  static const String THEME_IS_DARK_THEME = 'THEME_IS_DARK_THEME';

  static const String LANGUAGE_LANGUAGE_CODE_KEY = 'LANGUAGE_LANGUAGE_CODE_KEY';
  static const String LANGUAGE_COUNTRY_CODE_KEY = 'LANGUAGE_COUNTRY_CODE_KEY';
  static const String LANGUAGE_LANGUAGE_NAME_KEY = 'LANGUAGE_LANGUAGE_NAME_KEY';

  static const String TRUE = 'true';

  static const String PLATFORM = 'android';

  static const String FALSE = 'false';

  static const String VALUE_HOLDER_USER_ID = 'VALUE_HOLDER_USER_ID';
  static const String VALUE_HOLDER_MEMBER_ID = 'VALUE_HOLDER_MEMBER_ID';
  static const String VALUE_HOLDER_API_TOKEN = 'VALUE_HOLDER_API_TOKEN';
  static const String VALUE_HOLDER_CALL_ACCESS_TOKEN= 'VALUE_HOLDER_CALL_ACCESS_TOKEN';
  static const String VALUE_HOLDER_REFRESH_TOKEN ='VALUE_HOLDER_REFRESH_TOKEN';
  static const String VALUE_HOLDER_SESSION_ID= 'VALUE_HOLDER_SESSION_ID';
  static const String VALUE_HOLDER_NOTIFICATION_TOKEN = 'VALUE_HOLDER_NOTIFICATION_TOKEN';
  static const String VALUE_HOLDER_ASSIGNED_NUMBER = 'VALUE_HOLDER_ASSIGNED_NUMBER';
  static const String VALUE_HOLDER_INCOMING_CALL_NOTIFICATION_SETTING = 'VALUE_HOLDER_INCOMING_NOTIFICATION_SETTING';
  static const String VALUE_HOLDER_SMS_NOTIFICATION_SETTING = 'VALUE_HOLDER_SMS_NOTIFICATION_SETTING';
  static const String VALUE_HOLDER_NOTICE_NOTIFICATION_SETTING = 'VALUE_HOLDER_NOTICE_NOTIFICATION_SETTING';

  static const String VALUE_HOLDER_USER_NAME = 'VALUE_HOLDER_USER_NAME';
  static const String VALUE_HOLDER_USER_EMAIL = 'VALUE_HOLDER_USER_EMAIL';
  static const String VALUE_HOLDER_USER_PASSWORD = 'VALUE_HOLDER_USER_PASSWORD';
  static const String VALUE_HOLDER_SELECTED_SOUND = 'VALUE_HOLDER_SELECTED_SOUND';
  static const String VALUE_HOLDER_DEFAULT_COUNTRY_CODE = "VALUE_HOLDER_DEFAULT_COUNTRY_CODE";
  static const String VALUE_HOLDER_DEFAULT_WORKSPACE = "VALUE_HOLDER_DEFAULT_WORKSPACE";
  static const String VALUE_HOLDER_WORKSPACE_DETAIL = "VALUE_HOLDER_WORKSPACE_DETAIL";
  static const String VALUE_HOLDER_DEFAULT_CHANNEL = "VALUE_HOLDER_DEFAULT_CHANNEL";
  static const String VALUE_HOLDER_CHANNEL_LIST = "VALUE_HOLDER_CHANNEL_LIST";
  static const String VALUE_HOLDER_VOICE_TOKEN = "VALUE_HOLDER_VOICE_TOKEN";
  static const String VALUE_HOLDER_DEFAULT_LANGUAGE = "VALUE_HOLDER_DEFAULT_LANGUAGE";
  static const String VALUE_HOLDER_PROFILE_PICTURE = "VALUE_HOLDER_PROFILE_PICTURE";


  static const String APP_INFO_FORCE_UPDATE_MSG = 'APP_INFO_FORCE_UPDATE_MSG';
  static const String APP_INFO_FORCE_UPDATE_TITLE = 'APP_INFO_FORCE_UPDATE_TITLE';
  static const String VALUE_HOLDER_NOTIFICATION_SETTING = 'NOTIFICATION_SETTING';
  static const String VALUE_HOLDER_USER_PROFILE_IMAGE_PATH = 'VALUE_HOLDER_USER_PROFILE_IMAGE_PATH';
  static const String VALUE_HOLDER_USER_ONLINE_STATUS = 'VALUE_HOLDER_USER_ONLINE_STATUS';
  static const String VALUE_HOLDER_START_DATE = 'START_DATE';
  static const String VALUE_HOLDER_END_DATE = 'END_DATE';


  static const int REQUEST_CODE_MENU_NUMBER_SETTING = 1001;
  static const int REQUEST_CODE_MENU_HOME_FRAGMENT = 1005;
  static const int REQUEST_CODE_MENU_LATEST_PRODUCT_FRAGMENT = 1006;
  static const int REQUEST_CODE_MENU_SELECT_WHICH_USER_FRAGMENT = 1011;
  static const int REQUEST_CODE_MENU_BLOG_FRAGMENT = 1015;
  static const int REQUEST_CODE_MENU_MEMBER_LIST_FRAGMENT = 1016;
  static const int REQUEST_CODE_MENU_CALLS_FRAGMENT = 1020;
  static const int REQUEST_CODE_MENU_DIALER_FRAGMENT = 1026;

  static const int REQUEST_CODE_MENU_CONTACTS_FRAGMENT = 2008;

  static const int NOTIFICATION_CHANNEL_ID_CALL_INCOMING = 3;
  static const String NOTIFICATION_CHANNEL_CALL_INCOMING = "Incoming";
  static const String NOTIFICATION_CHANNEL_CALL_INCOMING_TOPIC = "incoming";

  static const String NOTIFICATION_SMS_CHANNEL = "SMS Notification";
  static const String NOTIFICATION_CHANNEL_SMS_TOPIC = "sms";

  static const int NOTIFICATION_CHANNEL_ID_CALL_IN_PROGRESS_OUTGOING = 4;
  static const String NOTIFICATION_CHANNEL_CALL_IN_PROGRESS_OUTGOING = "Call In Progress Outgoing";
  static const String NOTIFICATION_CHANNEL_CALL_IN_PROGRESS_TOPIC_OUTGOING = "call_in_progress_outgoing";

  static const int NOTIFICATION_CHANNEL_ID_CALL_IN_PROGRESS_INCOMING = 5;
  static const String NOTIFICATION_CHANNEL_CALL_IN_PROGRESS_INCOMING = "Call In Progress Incoming";
  static const String NOTIFICATION_CHANNEL_CALL_IN_PROGRESS_TOPIC_INCOMING = "call_in_progress_incoming";

  static const int NOTIFICATION_SMS_ID = 4;
}

class MessageBoxDecorationType
{
  static const String TOP = 'TOP';
  static const String MIDDLE = 'MIDDLE';
  static const String BOTTOM = 'BOTTOM';
}
