/// Flutter icons CustomIcon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcon
///      fonts:
///       - asset: fonts/CustomIcon.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class CustomIcon {
  CustomIcon._();

  static const _kFontFam = 'CustomIcon';
  static const String _kFontPkg = null;

  static const IconData icon_add_contact = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_add_image = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_alarm = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_arrow_head_right = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_arrow_left = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_arrow_right = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_arrow_up = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_back_space = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_call = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_call_1 = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_call_decline = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_call_delete = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_call_edit = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_chat = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_profile = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_dial_pad = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_incoming = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_logout = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_message = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_message_send = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_more_vertical = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_missed_call = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_new_message = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_outgoing = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_person = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_search = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_setting = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_speaker = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_toggle_password = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_trash = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_trash_outlined = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_users = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_wifi = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_arrow_down = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_more = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_plus = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_person_star = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_plus_rounded = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_settings = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_help = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_activity_selected = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_close = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_empty_team = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_drop_down = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fiber_manual_record = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_pin = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_activity_unselected = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_contact_selected = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_contact_unselected = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_record = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_dialer_unselected = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_dialer_selected = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_empty_number = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_contacts_unselected = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_contacts_selected = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_mores_selected = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_mores_unselected = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_circle = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_mic_unselected = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_mic_selected = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_stop = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_hold = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_notification = IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_attachment = IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_person_full = IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_tag = IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_voice_mail_play = IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_call_busy = IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_call_missed = IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_call_cancelled = IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_call_no_answer = IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_voice_mail = IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_transfer_call = IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_notes = IconData(0xe849, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_add_person = IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_call_incoming = IconData(0xe84b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_call_outgoing = IconData(0xe84c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_muted = IconData(0xe84d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_contacts_book = IconData(0xe84e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_book = IconData(0xe84f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_history = IconData(0xe850, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_add_notes = IconData(0xe851, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_tags_outlined = IconData(0xe852, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_invite = IconData(0xe853, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_gallery = IconData(0xe854, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_recording = IconData(0xe855, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_play = IconData(0xe856, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_pause = IconData(0xe857, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dog = IconData(0xf6d3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
